apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    service: example-pod
spec:
  containers:
    - name: backend
      image: ubuntu
      command:
        - "bash"
        - "-c"
      args:
        - "while true; do date > /tmp/index.html ; sleep 1; done"
      volumeMounts:
        - mountPath: /tmp # the mount point for volume
          name: content-volume # should match the volume name defined below
    - name: frontend
      image: trinitronx/python-simplehttpserver
      command:
        - "sh"
        - "-c"
      args:
        - "python -m SimpleHTTPServer 8080"
      ports:
        - containerPort: 8080
      volumeMounts:
      - mountPath: /var/www # we can define different mount point for different container
        name: content-volume
  volumes:
    - name: content-volume
      emptyDir: {}