apiVersion: v1
kind: Pod
metadata:
  name: nfs-volume-pod
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    imagePullPolicy: IfNotPresent
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Password1234
    volumeMounts:
    - name: mysql-storage
      mountPath: /var/lib/mysql
  - name: wordpress
    image: wordpress:4.8-apache
    imagePullPolicy: IfNotPresent
    env:
    - name: WORDPRESS_DB_HOST
      value: 127.0.0.1
    - name: WORDPRESS_DB_PASSWORD
      value: Password1234
  volumes:
  - name: mysql-storage
    nfs:
      server: 10.0.2.4
      path: /nfs/data1
