apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: jupyter
        image: tensorflow/tensorflow:1.5.1-gpu
        ports:
        - name: jupyter
          containerPort: 8888
        env:
        - name: TOKEN
          value: ""
        command: ["/bin/sh", "-c"]
        args: ["rm -r /notebooks/*;
                curl https://raw.githubusercontent.com/ogre0403/nchc-kubernetes-tutorial/master/advanced/01-Non-Distributed-TF/Non-Distributed.ipynb -o Non-Distributed.ipynb;
                /run_jupyter.sh --allow-root --NotebookApp.token=${TOKEN};"]
        resources:
          limits:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tf-master-service
  name: master
spec:
  selector:
    app: master
  ports:
  - name: jupyter
    port: 8888
    targetPort: 8888

