apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: blog
spec:
  type: ClusterIP
  ports:
    - port: 7070
      targetPort: 80
  selector:
    app: blog
    tier: wordpress