apiVersion: v1
kind: Service
metadata:
  name: wordpress-nodeport-svc
  labels:
    app: blog
spec:
  type: NodePort
  ports:
    - port: 7070
      targetPort: 80
  selector:
    app: blog
    tier: wordpress