apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: jupyter
        image: tensorflow/tensorflow:1.5.1
        ports:
        - name: jupyter
          containerPort: 8888
        env:
        - name: TOKEN
          value: ""
        command: ["/bin/sh", "-c"]
        args: ["rm -r /notebooks/*;
                curl https://raw.githubusercontent.com/ogre0403/nchc-kubernetes-tutorial/master/advanced/02-Distributed-TF-same-Container/ps.ipynb -o ps.ipynb;
                curl https://raw.githubusercontent.com/ogre0403/nchc-kubernetes-tutorial/master/advanced/02-Distributed-TF-same-Container/worker.ipynb -o worker.ipynb;
                /run_jupyter.sh --allow-root --NotebookApp.token=${TOKEN};"]

---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  selector:
    app: master
  type: NodePort
  ports:
  - name: jupyter
    port: 8888
    targetPort: 8888

