apiVersion: v1
kind: Pod
metadata:
  name: p100-gpu-pod
spec:
  restartPolicy: Never
  containers:
  - image: nvidia/cuda
    imagePullPolicy: IfNotPresent
    name: cuda
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
    accelerator: nvidia-tesla-p100 # or nvidia-tesla-k80 etc.