apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-server
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80