apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress-ingress
spec:
  rules:
  - host: blog.example.com
    http:
      paths:
      - backend:
          serviceName: wordpress-svc
          servicePort: 80
  - host: nginx.example.com
    http:
      paths:
      - backend:
          serviceName: nginx-svc
          servicePort: 80

