apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
      tier: wordpress
  replicas: 3
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: blog
        tier: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.8-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-svc:3360
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
